version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: >
      sh -c "python manage.py runserver 0:8000"
    environment:
      - DB_HOST="${DB_HOST}"
      - DB_NAME="${DB_NAME}"
      - DB_USER=${DB_USER}"
      - DB_PASSWORD="${DB_PASSWORD}"
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
